config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
  get '/about', to: "home#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "PinterestClone", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "About us", about_path, class:'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
      
      <% if user_signed_in? %>
        
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, class: 'nav-link', method: :delete  %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "List Pins", pins_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "New Pin", new_pin_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
           <%= link_to "Login", new_user_session_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Join", new_user_registration_path, class: 'nav-link'  %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us </h1>

<p> My name is Heraldo and I'm building a pinterest clone website! </p>

app/views/home/index.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron container">  
      <h1 class="display-3">Wellcome to my pinterest app</h1>
      <p> Pretty cool dont you think?</p>
      <% if user_signed_in? %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: 'btn btn-info'  %>
        <%= link_to "List Pins", pins_path, class: 'btn btn-success'  %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: 'btn btn-light'  %>
        <%= link_to "Join", new_user_registration_path, class: 'btn btn-info'  %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinterestClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'home/header' %>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class:"alert alert-info")%>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
   <%= form_with(model: pin, local: true) do |form| %>
    <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group-label">
    <%= form.label :description, class: 'form-group' %>
    <%= form.text_field :description, id: :pin_description, class: 'form-group' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-success' %>
  </div>
<% end %>
  
  </div>
</div>
</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>